### ISSUE TITLE
Setup Cloud Storage Buckets using Terraform

### ISSUE THREAD

**Issue by rawanmahdi** [DSC-McMaster-U/Auto-ML#142]
After the backend endpoints are setup, we should be able to upload the dataset that the user drops into our platform into a cloud storage bucket. 

Experiment with configuring a storage bucket in the main.tf file. Test it by uploading a sample dataset from kaggle. This doesnt have to be linked with our backend at this point. 

Tutorial:
- https://cloud.google.com/storage/docs/terraform-create-bucket-upload-object 

Terraform resource docs:
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket_object

**Comment by abedmohammed** [comment]
I made 2 branches

[cloud-storage-setup](https://github.com/DSC-McMaster-U/Auto-ML/tree/cloud-storage-setup) has the terraform changes to create a bucket on gcloud

[gcloud-test-upload](https://github.com/DSC-McMaster-U/Auto-ML/tree/gcloud-test-upload) has a PUT request that uploads the attached file to that bucket
