### ISSUE TITLE
helloworld.py Cloud Function Configuration using Terraform

### ISSUE THREAD

**Issue by rawanmahdi** [DSC-McMaster-U/Auto-ML#144]
Follow [this](https://cloud.google.com/functions/docs/tutorials/terraform
) google documentation tutorial, but instead try to deploy a python helloworld function as done by [this](https://towardsdatascience.com/deploying-python-functions-with-google-cloud-functions-557517865ba7). Feel free to experiment with the console like they did in the second tutorial, but try to get this ticket done as a terraform block in main.tf.

End goal is to implement this part of the architecture:
![image](https://github.com/DSC-McMaster-U/Auto-ML/assets/111605471/98d08628-935a-40aa-8ef8-ca6ebc4f2a6f)

Resources for later:
- GKE event trigger integration: https://cloud.google.com/eventarc/docs/gke/route-trigger-cloud-functions

**Comment by rawanmahdi** [comment]
@ausbennett cool! Do you think there's a way for us to have our backend being making these HTTP requests to the cloud function? I'm having a hard time finding any docs/tutorials for this but it looks like [this](https://medium.com/google-cloud/setup-and-invoke-cloud-functions-using-python-e801a8633096#:~:text=noted%20in%20setup.-,Python%20Code,-When%20calling%20the) covers it. If thats possible, then we might be able to handle all the datascience and ML logic in our cloud functions. What do you think?

**Comment by ausbennett** [comment]
If the end goal is to communicate to cloud storage to read/write data, using cloud functions is seems VERY redundant 

We will send a request from backend to cloud functions that will send a request to cloud storage?

**Is it possible to communicate directly to cloud storage? If so our backend should handle the reading and writing!**

**Comment by rawanmahdi** [comment]
@ausbennett So should we stick with the alternative of having everything be flush with the backend? So we'd be implementing ML, the EDA and any other GCP APIs we want to use straight out of our FastAPI endpoints. Shall we scrap the cloud functions?

**Comment by ausbennett** [comment]
@rawanmahdi Unless there is an advantage to cloud functions? We would just need to figure out how the backend will know which api url to talk to

- initially I think we would need to pass it as a env variable or smth to the docker backend build process?

Going to have to look into it
