### ISSUE TITLE
Trouble shoot Pods limit 

### ISSUE THREAD

**Issue by rawanmahdi** [DSC-McMaster-U/Auto-ML#145]

**Comment by ausbennett** [comment]
Backend, doesn't need exposure to port 80, setting it back to what it was config'd for port 8000 for internal use

**Comment by ausbennett** [comment]
Going to test the fix in this branch: [ausbennett-pod-fix](https://github.com/DSC-McMaster-U/Auto-ML/tree/ausbennett-pod-fix)
