### ISSUE TITLE
Frontend: Mockup for Welcome page

### ISSUE THREAD

**Issue by rawanmahdi** [DSC-McMaster-U/Auto-ML#61]
Mockup a _Welcome_ page. Should contain the navigation bar (#60), and should have high level instructions like:
1. Upload dataset
2. Auto EDA
3. ...

**Comment by Raymondtaoo** [comment]
https://www.figma.com/file/kSHcG6LM3VgLLP2271PWKy/welcome-page-automl?type=design&node-id=0%3A1&mode=design&t=tiO2yUAODJNIolGW-1
