### ISSUE TITLE
Frontend: Mockup for Upload page

### ISSUE THREAD

**Issue by rawanmahdi** [DSC-McMaster-U/Auto-ML#62]
Mockup the data upload page to contain dropbox/file selection. Should also contain navigation bar (#60)

**Comment by NicoleSorokin** [comment]
<img width="929" alt="upload-mockup" src="https://github.com/DSC-McMaster-U/Auto-ML/assets/85652961/499cdd3c-7157-4e68-bed8-2af78534fff3">

**Comment by NicoleSorokin** [comment]
The mockup for the upload page.
