### ISSUE TITLE
Cloud: experiment with containerized layers

### ISSUE THREAD

**Issue by rawanmahdi** [DSC-McMaster-U/Auto-ML#67]
play with containerizing seperate layers

**Comment by ausbennett** [comment]
I guess I will document my progress onto this ticket cause why not:

### Approach / Plan:
1. Learn kubernetes holistically(the fundamentals)
2. Follow a quickstart guide / tutorial on Google kubernetes engine (keep track of resources for future use)
3. Have a better understanding on what to do for next sprint

### Resources
**Kubernetes For Beginners**: https://www.youtube.com/watch?v=s_o8dwzRlu4&t=572s

**Comment by ausbennett** [comment]
# Some possible cloud ideas we can work on this sprint:
- creating docker files for each layer of our app (namely: front-end and backend, not sure about the ML layer if thats possible)
- (if we have access to gcp) configure github actions to build docker images and push to our artifact registry (gcp)
- Maybe create a simple kubernetes cluster with what we have of our app (just to get the ball rolling, and foundations stared)
- Potential for Terraform research / straightup trying to just implement (if its that simple)
