### ISSUE TITLE
Connect Backend Endpoint to GCP 

### ISSUE THREAD

**Issue by rawanmahdi** [DSC-McMaster-U/Auto-ML#87]
- research
- basic cloud storage

**Comment by abedmohammed** [comment]
@rawanmahdi @Raymondtaoo We found that setting up the GCP connection is gonna base on how our backend is deployed, so we are gonna focus on getting the backend on Kubernetes first

**Comment by rawanmahdi** [comment]
@abedmohammed  @andrewbovbel  @Raymondtaoo 

Relates to #86, so maybe we should merge this with the task of deploying a simple cluster. Here are some resource I was looking at for doing so:
 - Quickstart GKE app deployment: https://cloud.google.com/kubernetes-engine/docs/deploy-app-cluster
 - Linked this earlier as well, uses FastAPI and deploys on GKE. The backend dockerfile should be ready for this, I might just have to alter and test the yaml: https://medium.com/analytics-vidhya/deploying-a-ml-model-with-fastapi-on-google-kubernetes-engine-google-cloud-platform-bc2adbe0a35a
 Might want to try this with the frontend as well so we should work on the dockerfile for it
